/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gestioncourrier_design;

import classe.idGenerator;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lankoande
 */
public class formEnvoie extends javax.swing.JInternalFrame {

    /**
     * Creates new form formEnvoie
     */
    public formEnvoie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablepamel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomExpediteur = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtEmailExpediteur = new javax.swing.JTextField();
        txtPrenomExpediteur = new javax.swing.JTextField();
        txtNumPieceExpediteur = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbTypePieceExpediteur = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtNomDestinateur = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPrenomDestinateur = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNumCourrier = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNatureCourrier = new javax.swing.JTextField();
        txtDescriptionCourrier = new javax.swing.JTextField();
        txtPrixEst = new javax.swing.JTextField();
        txtPrixFac = new javax.swing.JTextField();
        btnValider = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        txtDateDepotCourrier = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        txtDestinationCourrier = new javax.swing.JTextField();
        txtPhoneExpediteur = new javax.swing.JFormattedTextField();
        txtPhoneDestinateur = new javax.swing.JFormattedTextField();
        btnNouveau = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCourrier = new javax.swing.JTable();
        btnSupprimer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnActualiser = new javax.swing.JButton();
        btnImprimer = new javax.swing.JButton();

        tablepamel.setBackground(new java.awt.Color(0, 0, 51));
        tablepamel.setForeground(new java.awt.Color(255, 255, 255));
        tablepamel.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tablepamel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablepamel.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        tablepamel.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Hack", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Expéditeur");

        txtNomExpediteur.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        txtNomExpediteur.setForeground(new java.awt.Color(51, 51, 51));
        txtNomExpediteur.setEnabled(false);

        txtEmailExpediteur.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        txtEmailExpediteur.setForeground(new java.awt.Color(51, 51, 51));
        txtEmailExpediteur.setEnabled(false);
        txtEmailExpediteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailExpediteurActionPerformed(evt);
            }
        });

        txtPrenomExpediteur.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        txtPrenomExpediteur.setForeground(new java.awt.Color(51, 51, 51));
        txtPrenomExpediteur.setEnabled(false);

        txtNumPieceExpediteur.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        txtNumPieceExpediteur.setForeground(new java.awt.Color(51, 51, 51));
        txtNumPieceExpediteur.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nom:");

        jLabel3.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Type piece:");

        jLabel5.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Prenom:");

        jLabel6.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Telephone:");

        jLabel7.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Num piece:");

        cmbTypePieceExpediteur.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        cmbTypePieceExpediteur.setForeground(new java.awt.Color(51, 51, 51));
        cmbTypePieceExpediteur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNIB", "Paspoot" }));
        cmbTypePieceExpediteur.setEnabled(false);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nom:");

        txtNomDestinateur.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        txtNomDestinateur.setForeground(new java.awt.Color(51, 51, 51));
        txtNomDestinateur.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Prenom:");

        txtPrenomDestinateur.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        txtPrenomDestinateur.setForeground(new java.awt.Color(51, 51, 51));
        txtPrenomDestinateur.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Telephone:");

        jLabel11.setFont(new java.awt.Font("Hack", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Destinteur");

        jLabel12.setFont(new java.awt.Font("Hack", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("Info Courrier");

        jLabel13.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Num courrier:");

        txtNumCourrier.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        txtNumCourrier.setForeground(new java.awt.Color(51, 51, 51));
        txtNumCourrier.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nature:");

        jLabel15.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Description:");

        jLabel16.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Prix estimer:");

        jLabel17.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Date de depot:");

        jLabel18.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Prix facturer");

        txtNatureCourrier.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        txtNatureCourrier.setForeground(new java.awt.Color(51, 51, 51));
        txtNatureCourrier.setEnabled(false);

        txtDescriptionCourrier.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        txtDescriptionCourrier.setForeground(new java.awt.Color(51, 51, 51));
        txtDescriptionCourrier.setEnabled(false);

        txtPrixEst.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        txtPrixEst.setForeground(new java.awt.Color(51, 51, 51));
        txtPrixEst.setEnabled(false);

        txtPrixFac.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        txtPrixFac.setForeground(new java.awt.Color(51, 51, 51));
        txtPrixFac.setEnabled(false);

        btnValider.setBackground(new java.awt.Color(0, 0, 51));
        btnValider.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        btnValider.setForeground(new java.awt.Color(255, 255, 255));
        btnValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/valided-blanc.png"))); // NOI18N
        btnValider.setText("Valider");
        btnValider.setEnabled(false);
        btnValider.setIconTextGap(6);
        btnValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderMouseClicked(evt);
            }
        });

        btnAnnuler.setBackground(new java.awt.Color(0, 0, 51));
        btnAnnuler.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        btnAnnuler.setForeground(new java.awt.Color(255, 255, 255));
        btnAnnuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel-blanc.png"))); // NOI18N
        btnAnnuler.setText("Annuler");
        btnAnnuler.setEnabled(false);
        btnAnnuler.setIconTextGap(6);
        btnAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnnulerMouseClicked(evt);
            }
        });

        txtDateDepotCourrier.setForeground(new java.awt.Color(0, 0, 0));
        txtDateDepotCourrier.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtDateDepotCourrier.setEnabled(false);
        txtDateDepotCourrier.setFont(new java.awt.Font("Hack", 2, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Destination:");

        txtDestinationCourrier.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        txtDestinationCourrier.setForeground(new java.awt.Color(51, 51, 51));
        txtDestinationCourrier.setEnabled(false);

        txtPhoneExpediteur.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtPhoneExpediteur.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## ## ## ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPhoneExpediteur.setEnabled(false);
        txtPhoneExpediteur.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N

        txtPhoneDestinateur.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtPhoneDestinateur.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## ## ## ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPhoneDestinateur.setEnabled(false);
        txtPhoneDestinateur.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N

        btnNouveau.setBackground(new java.awt.Color(0, 0, 51));
        btnNouveau.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        btnNouveau.setForeground(new java.awt.Color(255, 255, 255));
        btnNouveau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nouveau -blanc.png"))); // NOI18N
        btnNouveau.setText("Nouveau");
        btnNouveau.setIconTextGap(6);
        btnNouveau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNouveauMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomExpediteur)
                            .addComponent(txtEmailExpediteur, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(cmbTypePieceExpediteur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrenomExpediteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhoneExpediteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumPieceExpediteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrenomDestinateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomDestinateur, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtPhoneDestinateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDescriptionCourrier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(txtDateDepotCourrier))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNumCourrier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel14)
                                .addGap(15, 15, 15)
                                .addComponent(txtNatureCourrier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDestinationCourrier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147)
                                .addComponent(btnNouveau)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(btnAnnuler)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                    .addComponent(txtPrixEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrixFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(30, 30, 30))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbTypePieceExpediteur, txtDescriptionCourrier, txtDestinationCourrier, txtEmailExpediteur, txtNatureCourrier, txtNomDestinateur, txtNomExpediteur, txtNumCourrier, txtNumPieceExpediteur, txtPhoneDestinateur, txtPhoneExpediteur, txtPrenomDestinateur, txtPrenomExpediteur, txtPrixEst, txtPrixFac});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel18});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnnuler, btnNouveau, btnValider});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomExpediteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtEmailExpediteur, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(cmbTypePieceExpediteur, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumPieceExpediteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtNomDestinateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrenomDestinateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtPhoneDestinateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtPrenomExpediteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtPhoneExpediteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNumCourrier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtNatureCourrier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrixEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtDescriptionCourrier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(txtPrixFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateDepotCourrier, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtDestinationCourrier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAnnuler)
                        .addComponent(btnNouveau)
                        .addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDescriptionCourrier, txtDestinationCourrier, txtEmailExpediteur, txtNatureCourrier, txtNomDestinateur, txtNomExpediteur, txtNumCourrier, txtNumPieceExpediteur, txtPhoneDestinateur, txtPhoneExpediteur, txtPrenomDestinateur, txtPrenomExpediteur, txtPrixEst, txtPrixFac});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel18});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAnnuler, btnNouveau, btnValider});

        tablepamel.addTab("Enregistrer de courrier a envoyer", jPanel1);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setFont(new java.awt.Font("Hack", 2, 14)); // NOI18N

        tableCourrier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Courrier", "Nature", "Date", "prix", "Expediteur", "Destinateur", "Destination", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableCourrier);

        btnSupprimer.setBackground(new java.awt.Color(0, 0, 51));
        btnSupprimer.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        btnSupprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete-blanc.png"))); // NOI18N
        btnSupprimer.setText("Supprimer");
        btnSupprimer.setEnabled(false);
        btnSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimerMouseClicked(evt);
            }
        });

        btnModifier.setBackground(new java.awt.Color(0, 0, 51));
        btnModifier.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        btnModifier.setForeground(new java.awt.Color(255, 255, 255));
        btnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update-blanc.png"))); // NOI18N
        btnModifier.setText("Modifier");
        btnModifier.setEnabled(false);
        btnModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierMouseClicked(evt);
            }
        });
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnActualiser.setBackground(new java.awt.Color(0, 0, 51));
        btnActualiser.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        btnActualiser.setForeground(new java.awt.Color(255, 255, 255));
        btnActualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualiser-blanc.png"))); // NOI18N
        btnActualiser.setText("Actualiser");
        btnActualiser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualiserMouseClicked(evt);
            }
        });
        btnActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiserActionPerformed(evt);
            }
        });

        btnImprimer.setBackground(new java.awt.Color(0, 0, 51));
        btnImprimer.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        btnImprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imprimante-blanc.png"))); // NOI18N
        btnImprimer.setText("Imprimer");
        btnImprimer.setEnabled(false);
        btnImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnSupprimer)
                .addGap(55, 55, 55)
                .addComponent(btnModifier)
                .addGap(55, 55, 55)
                .addComponent(btnActualiser)
                .addGap(55, 55, 55)
                .addComponent(btnImprimer)
                .addGap(120, 174, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnActualiser, btnImprimer, btnModifier, btnSupprimer});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifier)
                    .addComponent(btnSupprimer)
                    .addComponent(btnActualiser)
                    .addComponent(btnImprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnActualiser, btnImprimer, btnModifier, btnSupprimer});

        tablepamel.addTab("Liste des courriers envoyer", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tablepamel, javax.swing.GroupLayout.PREFERRED_SIZE, 1119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablepamel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailExpediteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailExpediteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailExpediteurActionPerformed

    private void btnSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMouseClicked

//        String code = (String) tableCourrier.getValueAt(tableCourrier.getSelectedRow(), 1).toString();
//        DefaultTableModel tm = (DefaultTableModel) tableCourrier.getModel();
//        try {
//            Article.supprimer(code);
//        } catch (SQLException | ClassNotFoundException ex) {
//            Logger.getLogger(formArticle.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        tm.setRowCount(0);
//        try {
//
//            Article.actualiser(tm);
//
//            if (tableCourrier.getRowCount() != 0) {
//
//                btnImprimer.setEnabled(true);
//                btnSupprimer.setEnabled(false);
//                btnModifier.setEnabled(false);
//            }
//        } catch (SQLException | ClassNotFoundException ex) {
//            Logger.getLogger(formArticle.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnSupprimerMouseClicked

    private void btnModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierMouseClicked
//        DefaultTableModel tm = (DefaultTableModel) tableCourrier.getModel();
//
//        String code = (String) tableCourrier.getValueAt(tableCourrier.getSelectedRow(), 1).toString();
//        String libelle = (String) tableCourrier.getValueAt(tableCourrier.getSelectedRow(), 2).toString();
//        try {
//
//            Article.modifier(code, libelle);
//            tm.setRowCount(0);
//            Article.actualiser(tm);
//            if (tableCourrier.getRowCount() != 0) {
//                btnImprimer.setEnabled(true);
//                btnSupprimer.setEnabled(false);
//                btnModifier.setEnabled(false);
//            }
//        } catch (SQLException | ClassNotFoundException ex) {
//            Logger.getLogger(formArticle.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnModifierMouseClicked

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnActualiserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualiserMouseClicked
//        DefaultTableModel tm = (DefaultTableModel) tableCourrier.getModel();
//        tm.setRowCount(0);
//        try {
//            Article.actualiser(tm);
//            if (tableCourrier.getRowCount() != 0) {
//                btnImprimer.setEnabled(true);
//                btnSupprimer.setEnabled(false);
//                btnModifier.setEnabled(false);
//            }
//        } catch (SQLException | ClassNotFoundException ex) {
//            Logger.getLogger(formArticle.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnActualiserMouseClicked

    private void btnActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualiserActionPerformed

    private void btnImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimerActionPerformed

    private void btnNouveauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNouveauMouseClicked

        allActive();
        try {
            txtNumCourrier.setText(Long.toString(idGenerator.generateUniqueId()));
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(formEnvoie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNouveauMouseClicked

    private void btnAnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnnulerMouseClicked

        allRemouve();  //vidage des champs
        allDesactive(); //desactivation des champs
    }//GEN-LAST:event_btnAnnulerMouseClicked

    private void btnValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderMouseClicked
        if (txtNomExpediteur.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le Nom de l'expediteur ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtNomExpediteur.requestFocus();

        } else if (txtPrenomExpediteur.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le Prenom de l'expediteur ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtPrenomExpediteur.requestFocus();

        } else if (txtPhoneExpediteur.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le numero de telephone de l'expediteur ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtPhoneExpediteur.requestFocus();

        } else if (txtNumPieceExpediteur.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le Numero de la piece de l'expediteur ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtNumPieceExpediteur.requestFocus();

        } else if (txtNomDestinateur.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le Nom du destinateur ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtNomDestinateur.requestFocus();

        } else if (txtPrenomDestinateur.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le Prenom du destinateur ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtPrenomDestinateur.requestFocus();

        } else if (txtPhoneDestinateur.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le Numero telephonique  du destinateur ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtPhoneDestinateur.requestFocus();

        } else if (txtNatureCourrier.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "La Nature Non du courrier ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtNatureCourrier.requestFocus();

        } else if (txtPrixEst.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le prix d'estimation du courrier ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtPrixEst.requestFocus();

        } else if (txtDescriptionCourrier.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le la description du courrier ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtDescriptionCourrier.requestFocus();

        } else if (txtDateDepotCourrier.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "La date de depot du courrierne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtDateDepotCourrier.requestFocus();

        } else if (txtPrixFac.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le prix de facturation du courrier ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtPrixFac.requestFocus();

        } else if (txtDestinationCourrier.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "La destinatio du courrier ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtDestinationCourrier.requestFocus();

        } else {
            // recuperationd des valeurs saisie dna les champs

            String NomExpediteur = txtNomExpediteur.getText();
            String prenomExpediteur = txtPrenomExpediteur.getText();
            String emailExpediteur = txtEmailExpediteur.getText();
            String phoneExpediteur = txtPhoneExpediteur.getText();
            String typePieceExpediteur = (String) cmbTypePieceExpediteur.getSelectedItem();
            String numPieceExpediteur = txtNumPieceExpediteur.getText();
            String nomDestinateur = txtNomDestinateur.getText();
            String renomDestinateur = txtPrenomDestinateur.getText();
            String phoneDestinateur = txtPhoneDestinateur.getText();
            String numCourrier = txtNumCourrier.getText();
            String natureCourrier = txtNatureCourrier.getText();
            String prixEst = txtPrixEst.getText();
            String descriptionCourrier = txtDescriptionCourrier.getText();
            String dateDepotCourrier = txtDateDepotCourrier.getText();
            String prixFac = txtPrixFac.getText();
            String destinationCourrier = txtDestinationCourrier.getText();

        }
    }//GEN-LAST:event_btnValiderMouseClicked

    // Fonctions
    private void allActive() {
        btnValider.setEnabled(true);
        btnAnnuler.setEnabled(true);

        // activation de tout les champs sauf num courrier
        txtNomExpediteur.setEnabled(true);
        txtPrenomExpediteur.setEnabled(true);
        txtEmailExpediteur.setEnabled(true);
        txtPhoneExpediteur.setEnabled(true);
        cmbTypePieceExpediteur.setEnabled(true);
        txtNumPieceExpediteur.setEnabled(true);
        txtNomDestinateur.setEnabled(true);
        txtPrenomDestinateur.setEnabled(true);
        txtPhoneDestinateur.setEnabled(true);
        txtNatureCourrier.setEnabled(true);
        txtPrixEst.setEnabled(true);
        txtDescriptionCourrier.setEnabled(true);
        txtDateDepotCourrier.setEnabled(true);
        txtPrixFac.setEnabled(true);
        txtDestinationCourrier.setEnabled(true);
    }

    private void allDesactive() {   // Desactivation de tous les champs et boutton faus le boutton nouveau
        btnValider.setEnabled(false);
        btnAnnuler.setEnabled(false);

        // activation de tout les champs sauf num courrier
        txtNomExpediteur.setEnabled(false);
        txtPrenomExpediteur.setEnabled(false);
        txtEmailExpediteur.setEnabled(false);
        txtPhoneExpediteur.setEnabled(false);
        cmbTypePieceExpediteur.setEnabled(false);
        txtNumPieceExpediteur.setEnabled(false);
        txtNomDestinateur.setEnabled(false);
        txtPrenomDestinateur.setEnabled(false);
        txtPhoneDestinateur.setEnabled(false);
        txtNatureCourrier.setEnabled(false);
        txtPrixEst.setEnabled(false);
        txtDescriptionCourrier.setEnabled(false);
        txtDateDepotCourrier.setEnabled(false);
        txtPrixFac.setEnabled(false);
        txtDestinationCourrier.setEnabled(false);
    }

    private void allRemouve() {
        txtNomExpediteur.setText(null);
        txtPrenomExpediteur.setText(null);
        txtEmailExpediteur.setText(null);
        txtPhoneExpediteur.setText(null);
        cmbTypePieceExpediteur.setSelectedIndex(0);
        txtNumPieceExpediteur.setText(null);
        txtNomDestinateur.setText(null);
        txtPrenomDestinateur.setText(null);
        txtPhoneDestinateur.setText(null);
        txtNumCourrier.setText(null);
        txtNatureCourrier.setText(null);
        txtPrixEst.setText(null);
        txtDescriptionCourrier.setText(null);
        txtDateDepotCourrier.setText(null);
        txtPrixFac.setText(null);
        txtDestinationCourrier.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualiser;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnImprimer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnNouveau;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnValider;
    private javax.swing.JComboBox<String> cmbTypePieceExpediteur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tableCourrier;
    private javax.swing.JTabbedPane tablepamel;
    private javax.swing.JFormattedTextField txtDateDepotCourrier;
    private javax.swing.JTextField txtDescriptionCourrier;
    private javax.swing.JTextField txtDestinationCourrier;
    private javax.swing.JTextField txtEmailExpediteur;
    private javax.swing.JTextField txtNatureCourrier;
    private javax.swing.JTextField txtNomDestinateur;
    private javax.swing.JTextField txtNomExpediteur;
    private javax.swing.JTextField txtNumCourrier;
    private javax.swing.JTextField txtNumPieceExpediteur;
    private javax.swing.JFormattedTextField txtPhoneDestinateur;
    private javax.swing.JFormattedTextField txtPhoneExpediteur;
    private javax.swing.JTextField txtPrenomDestinateur;
    private javax.swing.JTextField txtPrenomExpediteur;
    private javax.swing.JTextField txtPrixEst;
    private javax.swing.JTextField txtPrixFac;
    // End of variables declaration//GEN-END:variables
}
