/**
 *
 *
 *this is LANKOANDE Urbain code
 * Prince.COM << lankoandeurbain8@gmail.com >>
 *
 */
package gestioncourrier_design;

import classe.client;
import classe.courrier;
import classe.exportPdf;
import classe.idGenerator;
import java.io.File;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lankoande
 */
public final class formReception extends javax.swing.JInternalFrame {

    /**
     * Creates new form formReception
     */
    public formReception() {
        initComponents();
        numrecup.setVisible(false);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        allDesactive();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNumRech = new javax.swing.JTextField();
        btnRecherche = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        txtDateEnvoie = new javax.swing.JTextField();
        txtProvenance = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbTypePiece = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtNumPiece = new javax.swing.JTextField();
        btnAnnuler = new javax.swing.JButton();
        btnValider = new javax.swing.JButton();
        txtPhone = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtExpediteur = new javax.swing.JTextField();
        txtDestinataire = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDateRecuperer = new com.toedter.calendar.JDateChooser();
        numrecup = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCourrierRecuperer = new javax.swing.JTable();
        btnSupprimer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnActualiser = new javax.swing.JButton();
        btnExporter = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(240, 65));

        tabPanel.setBackground(new java.awt.Color(0, 0, 51));
        tabPanel.setForeground(new java.awt.Color(255, 255, 255));
        tabPanel.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        tabPanel.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Hack", 3, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Recherche de courrier");

        jLabel2.setFont(new java.awt.Font("Hack", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Type:");

        txtNumRech.setFont(new java.awt.Font("Hack", 2, 15)); // NOI18N
        txtNumRech.setText("num courrier");
        txtNumRech.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumRechFocusGained(evt);
            }
        });

        btnRecherche.setBackground(new java.awt.Color(0, 0, 51));
        btnRecherche.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        btnRecherche.setForeground(new java.awt.Color(255, 255, 255));
        btnRecherche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rechercher-blanc.png"))); // NOI18N
        btnRecherche.setText("Rechercher");
        btnRecherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRechercheMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Hack", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Date d'envoie:");

        jLabel4.setFont(new java.awt.Font("Hack", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Date recuperation:");

        jLabel5.setFont(new java.awt.Font("Hack", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Provenance:");

        jLabel6.setFont(new java.awt.Font("Hack", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Destination:");

        txtType.setFont(new java.awt.Font("Hack", 2, 15)); // NOI18N
        txtType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtType.setEnabled(false);

        txtDateEnvoie.setFont(new java.awt.Font("Hack", 2, 15)); // NOI18N
        txtDateEnvoie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDateEnvoie.setEnabled(false);

        txtProvenance.setFont(new java.awt.Font("Hack", 2, 15)); // NOI18N
        txtProvenance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProvenance.setEnabled(false);

        txtDestination.setFont(new java.awt.Font("Hack", 2, 15)); // NOI18N
        txtDestination.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDestination.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Info  designataire");

        jLabel8.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nom:");

        txtNom.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        txtNom.setForeground(new java.awt.Color(51, 51, 51));

        jLabel9.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Prenom:");

        txtPrenom.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        txtPrenom.setForeground(new java.awt.Color(51, 51, 51));

        jLabel10.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Telephone:");

        jLabel12.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Type piece:");

        cmbTypePiece.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        cmbTypePiece.setForeground(new java.awt.Color(51, 51, 51));
        cmbTypePiece.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNIB", "Passeport" }));

        jLabel13.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Num piece:");

        txtNumPiece.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N
        txtNumPiece.setForeground(new java.awt.Color(51, 51, 51));

        btnAnnuler.setBackground(new java.awt.Color(102, 102, 102));
        btnAnnuler.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        btnAnnuler.setForeground(new java.awt.Color(255, 255, 255));
        btnAnnuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel-blanc.png"))); // NOI18N
        btnAnnuler.setText("Annuler");
        btnAnnuler.setIconTextGap(6);

        btnValider.setBackground(new java.awt.Color(0, 0, 51));
        btnValider.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        btnValider.setForeground(new java.awt.Color(255, 255, 255));
        btnValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/valided-blanc.png"))); // NOI18N
        btnValider.setText("Valider");
        btnValider.setIconTextGap(6);
        btnValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderMouseClicked(evt);
            }
        });

        try {
            txtPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## ## ## ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setFont(new java.awt.Font("Hack", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Expéditeur:");

        txtExpediteur.setFont(new java.awt.Font("Hack", 2, 15)); // NOI18N
        txtExpediteur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtExpediteur.setEnabled(false);

        txtDestinataire.setFont(new java.awt.Font("Hack", 2, 15)); // NOI18N
        txtDestinataire.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDestinataire.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Hack", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Destinataire:");

        txtDateRecuperer.setForeground(new java.awt.Color(51, 51, 51));
        txtDateRecuperer.setFont(new java.awt.Font("Hack", 2, 13)); // NOI18N

        numrecup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numrecupActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 0, 51));
        btnUpdate.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mettre-a-jour (1).png"))); // NOI18N
        btnUpdate.setText("Modifier");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 0, 51));
        btnDelete.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete-blanc.png"))); // NOI18N
        btnDelete.setText("Supprimer");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtProvenance, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(205, 205, 205)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtExpediteur, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)
                                .addComponent(jLabel14))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(txtDateRecuperer, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtNumRech, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                                .addComponent(btnRecherche)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel3)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(txtDateEnvoie, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDestinataire, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(20, 20, 20)
                                        .addComponent(txtNom))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(20, 20, 20)
                                        .addComponent(cmbTypePiece, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNumPiece)))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDelete)
                            .addComponent(btnUpdate)
                            .addComponent(btnAnnuler)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(numrecup, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnValider)
                .addGap(109, 109, 109))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel6});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel12, jLabel13, jLabel8, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbTypePiece, txtNom, txtPhone, txtPrenom});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDateEnvoie, txtDestinataire, txtDestination, txtExpediteur, txtProvenance, txtType});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnnuler, btnDelete, btnUpdate, btnValider});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumRech, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateEnvoie, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProvenance, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtExpediteur, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4)
                            .addComponent(txtDestinataire, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDateRecuperer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numrecup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(cmbTypePiece, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtNumPiece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnnuler))))
                .addGap(98, 98, 98))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel12, jLabel13, jLabel8, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbTypePiece, txtNom, txtNumPiece, txtPhone, txtPrenom});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDateEnvoie, txtDestinataire, txtDestination, txtExpediteur, txtProvenance, txtType});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAnnuler, btnDelete, btnUpdate, btnValider});

        tabPanel.addTab("Enregistrement de la recuperation d'un courrier", jPanel1);

        tableCourrierRecuperer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num courrier", "Type", "Date envoie", "Provenance", "Destination", "Expediteur", "Destinataire", "Date recuperation", "Recuperateur"
            }
        ));
        tableCourrierRecuperer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCourrierRecupererMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCourrierRecuperer);
        if (tableCourrierRecuperer.getColumnModel().getColumnCount() > 0) {
            tableCourrierRecuperer.getColumnModel().getColumn(0).setPreferredWidth(20);
            tableCourrierRecuperer.getColumnModel().getColumn(1).setPreferredWidth(30);
            tableCourrierRecuperer.getColumnModel().getColumn(2).setPreferredWidth(50);
            tableCourrierRecuperer.getColumnModel().getColumn(3).setPreferredWidth(50);
            tableCourrierRecuperer.getColumnModel().getColumn(4).setPreferredWidth(50);
            tableCourrierRecuperer.getColumnModel().getColumn(5).setPreferredWidth(50);
            tableCourrierRecuperer.getColumnModel().getColumn(6).setPreferredWidth(50);
            tableCourrierRecuperer.getColumnModel().getColumn(7).setPreferredWidth(50);
            tableCourrierRecuperer.getColumnModel().getColumn(8).setPreferredWidth(50);
        }

        btnSupprimer.setBackground(new java.awt.Color(0, 0, 51));
        btnSupprimer.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        btnSupprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete-blanc.png"))); // NOI18N
        btnSupprimer.setText("Supprimer");
        btnSupprimer.setEnabled(false);
        btnSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimerMouseClicked(evt);
            }
        });

        btnModifier.setBackground(new java.awt.Color(0, 0, 51));
        btnModifier.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        btnModifier.setForeground(new java.awt.Color(255, 255, 255));
        btnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update-blanc.png"))); // NOI18N
        btnModifier.setText("Modifier");
        btnModifier.setEnabled(false);
        btnModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierMouseClicked(evt);
            }
        });
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnActualiser.setBackground(new java.awt.Color(0, 0, 51));
        btnActualiser.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        btnActualiser.setForeground(new java.awt.Color(255, 255, 255));
        btnActualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualiser-blanc.png"))); // NOI18N
        btnActualiser.setText("Actualiser");
        btnActualiser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualiserMouseClicked(evt);
            }
        });
        btnActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiserActionPerformed(evt);
            }
        });

        btnExporter.setBackground(new java.awt.Color(0, 0, 51));
        btnExporter.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        btnExporter.setForeground(new java.awt.Color(255, 255, 255));
        btnExporter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imprimante-blanc.png"))); // NOI18N
        btnExporter.setText("Imprimer");
        btnExporter.setEnabled(false);
        btnExporter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExporterMouseClicked(evt);
            }
        });
        btnExporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExporterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(btnSupprimer)
                .addGap(55, 55, 55)
                .addComponent(btnModifier)
                .addGap(55, 55, 55)
                .addComponent(btnActualiser)
                .addGap(55, 55, 55)
                .addComponent(btnExporter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnActualiser, btnExporter, btnModifier, btnSupprimer});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifier)
                    .addComponent(btnSupprimer)
                    .addComponent(btnActualiser)
                    .addComponent(btnExporter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnActualiser, btnExporter, btnModifier, btnSupprimer});

        tabPanel.addTab("Liste des courriers recuperer", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMouseClicked

        //        String code = (String) tableCourrier.getValueAt(tableCourrier.getSelectedRow(), 1).toString();
        //        DefaultTableModel tm = (DefaultTableModel) tableCourrier.getModel();
        //        try {
        //            Article.supprimer(code);
        //        } catch (SQLException | ClassNotFoundException ex) {
        //            Logger.getLogger(formArticle.class.getName()).log(Level.SEVERE, null, ex);
        //        }
        //        tm.setRowCount(0);
        //        try {
        //
        //            Article.actualiser(tm);
        //
        //            if (tableCourrier.getRowCount() != 0) {
        //
        //                btnImprimer.setEnabled(true);
        //                btnSupprimer.setEnabled(false);
        //                btnModifier.setEnabled(false);
        //            }
        //        } catch (SQLException | ClassNotFoundException ex) {
        //            Logger.getLogger(formArticle.class.getName()).log(Level.SEVERE, null, ex);
        //        }
    }//GEN-LAST:event_btnSupprimerMouseClicked

    private void btnModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierMouseClicked

    }//GEN-LAST:event_btnModifierMouseClicked

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnActualiserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualiserMouseClicked
        DefaultTableModel tm = (DefaultTableModel) tableCourrierRecuperer.getModel();
        tm.setRowCount(0);
        try {
            courrier.actualiserListRecuperer(tm);
            if (tableCourrierRecuperer.getRowCount() != 0) {
                btnExporter.setEnabled(true);
                btnSupprimer.setEnabled(false);
                btnModifier.setEnabled(false);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(formReception.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualiserMouseClicked

    private void btnActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualiserActionPerformed

    private void btnExporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExporterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExporterActionPerformed

    private void btnValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderMouseClicked
        if (txtDateRecuperer.getDate() == null) {
            JOptionPane.showMessageDialog(rootPane, "La date de retrait du courrier ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtDateRecuperer.requestFocus();
        } else if (txtNom.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le nom du recuperateur ne pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtNom.requestFocus();
        } else if (txtPrenom.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le prenom du recuperateur ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtPrenom.requestFocus();
        } else if (txtPhone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le numero de telephone ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtPhone.requestFocus();
        } else if (txtNumPiece.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le numero de la piece ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtNumPiece.requestFocus();
        } else {
            String numRecuperateur = null;
            try {
                numRecuperateur = "R-" + Long.toString(idGenerator.generateUniqueId());
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(formEnvoie.class.getName()).log(Level.SEVERE, null, ex);
            }
            String numCourrier = txtNumRech.getText();
            DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy"); // creation d'un formatage de date
            String dateRetrait = dateFormat.format(txtDateRecuperer.getDate()); // formatage de la date et conversion et String
            String nom = txtNom.getText();
            String prenom = txtPrenom.getText();
            String phone = txtPhone.getText();
            String typePiece = (String) cmbTypePiece.getSelectedItem();
            String numpiece = txtNumPiece.getText();

            try {
                //            Envoie des donner dans la Data base
                courrier.validRetraisColis(numCourrier, dateRetrait, numRecuperateur);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(formReception.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                client.validerClient(numRecuperateur, nom, prenom, phone, typePiece, numpiece);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(formReception.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Enregistrement Effectuer!");
            allClear();
            allDesactive();
        }

    }//GEN-LAST:event_btnValiderMouseClicked

    private void btnRechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRechercheMouseClicked
        try {
            String[] result = courrier.rechercheColis(txtNumRech.getText());
            switch (result.length) {
                case 1 -> {
                    JOptionPane.showMessageDialog(null, "Colis Deja recuperer!");
                    allClear();
                    allDesactive();
                }
                case 2 -> {
                    JOptionPane.showMessageDialog(null, "Colis mon trouver!");
                    allClear();
                    allDesactive();
                }
                default -> {
                    txtType.setText(result[0]);
                    txtDateEnvoie.setText(result[1]);
                    txtProvenance.setText(result[2]);
                    txtDestination.setText(result[3]);
                    txtExpediteur.setText(result[4]);
                    txtDestinataire.setText(result[5]);
                    allActive();
                    txtDateRecuperer.requestFocus();
                }
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(formReception.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRechercheMouseClicked

    private void txtNumRechFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumRechFocusGained
        txtNumRech.setText(null);
    }//GEN-LAST:event_txtNumRechFocusGained

    private void btnExporterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExporterMouseClicked
        SimpleDateFormat formatter = new SimpleDateFormat("yyyyMMdd_HHmmss");
        Date date = new Date();
        String userHomeDirectory = System.getProperty("user.home");
//        System.out.print(userHomeDirectory);
        String directoryPath = userHomeDirectory + File.separator + "Documents/";
        String fileName = "listeCourrierRecuperer" + formatter.format(date) + ".pdf";
        exportPdf.exportTableToPdf(tableCourrierRecuperer, directoryPath + fileName);
    }//GEN-LAST:event_btnExporterMouseClicked

    private void tableCourrierRecupererMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCourrierRecupererMouseClicked

        DefaultTableModel dtm = (DefaultTableModel) tableCourrierRecuperer.getModel();
        int tIndex = tableCourrierRecuperer.getSelectedRow();
        txtNumRech.setText(dtm.getValueAt(tIndex, 0).toString());

        try {
            if (null == courrier.rechercheColisToupdate(txtNumRech.getText())) {
                JOptionPane.showMessageDialog(null, "<html> Il y a un probleme <br> Veillez contactez l'administrateur!</html>");
            } else {

                String[] result;
                result = courrier.rechercheColisToupdate(txtNumRech.getText());

                txtType.setText(result[0]);
                txtDateEnvoie.setText(result[1]);
                txtProvenance.setText(result[2]);
                txtDestination.setText(result[3]);
                txtExpediteur.setText(result[4]);
                txtDestinataire.setText(result[5]);
                txtDateRecuperer.setDate(null);
                numrecup.setText(result[6]);
                txtNom.setText(result[7]);
                txtPrenom.setText(result[8]);
                txtPhone.setText(result[9]);
                if ("CNIB".equals(result[10])) {
                    cmbTypePiece.setSelectedIndex(0);
                } else {
                    cmbTypePiece.setSelectedIndex(1);
                }
                txtNumPiece.setText(result[11]);

                allActive();
                txtNumRech.setEnabled(false);
                tabPanel.setSelectedComponent(jPanel1);
                btnUpdate.setEnabled(true);
                btnDelete.setEnabled(true);
                btnValider.setEnabled(false);
                btnRecherche.setEnabled(false);
                btnRecherche.enable(false);
                tabPanel.setSelectedComponent(jPanel1);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(formEnvoie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tableCourrierRecupererMouseClicked

    private void numrecupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numrecupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numrecupActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        try {
            if (JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment effectuer la suppresion [ ", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                courrier.ModiferCourrierReception(txtNumRech.getText());
                client.supprimerClient(numrecup.getText());

                allDesactive();
                allClear();
                btnDelete.setEnabled(false);
                btnUpdate.setEnabled(false);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FormUtilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        if (txtDateRecuperer.getDate() == null) {
            JOptionPane.showMessageDialog(rootPane, "La date de retrait du courrier ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtDateRecuperer.requestFocus();
        } else if (txtNom.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le nom du recuperateur ne pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtNom.requestFocus();
        } else if (txtPrenom.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le prenom du recuperateur ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtPrenom.requestFocus();
        } else if (txtPhone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le numero de telephone ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtPhone.requestFocus();
        } else if (txtNumPiece.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Le numero de la piece ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtNumPiece.requestFocus();
        } else {
            String numRecuperateur = numrecup.getText();
            String numCourrier = txtNumRech.getText();
            DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy"); // creation d'un formatage de date
            String dateRetrait = dateFormat.format(txtDateRecuperer.getDate()); // formatage de la date et conversion et String
            String nom = txtNom.getText();
            String prenom = txtPrenom.getText();
            String phone = txtPhone.getText();
            String typePiece = (String) cmbTypePiece.getSelectedItem();
            String numpiece = txtNumPiece.getText();

            try {
                //            Envoie des donner dans la Data base
                courrier.validRetraisColis(numCourrier, dateRetrait, numRecuperateur);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(formReception.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                client.ModifierClient(numRecuperateur, nom, prenom, phone, typePiece, numpiece);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(formReception.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Modification effectuer Effectuer!");
            allClear();
            allDesactive();

        }

    }//GEN-LAST:event_btnUpdateMouseClicked

    /**
     * Fonction pour desactiver les champs de saisie et les bouttons de controle
     */
    public void allDesactive() {
        txtDateRecuperer.enable(false);
        txtNom.enable(false);
        txtPrenom.enable(false);
        txtPhone.enable(false);
        cmbTypePiece.enable(false);
        txtNumPiece.enable(false);
        btnAnnuler.enable(false);
        btnValider.enable(false);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        txtNumRech.setEnabled(true);
        btnRecherche.setEnabled(true);

    }

    /**
     * Fonction pour activer les champs de saisie et les bouttons de controle
     */
    public void allActive() {
        txtDateRecuperer.enable(true);
        txtNom.enable(true);
        txtPrenom.enable(true);
        txtPhone.enable(true);
        cmbTypePiece.enable(true);
        txtNumPiece.enable(true);
        btnAnnuler.enable(true);
        btnValider.enable(true);

    }

    /**
     * fonction pour vider les champs
     */
    public void allClear() {
        txtNumRech.setText(null);
        txtType.setText(null);
        txtDateEnvoie.setText(null);
        txtExpediteur.setText(null);
        txtDestinataire.setText(null);
        txtProvenance.setText(null);
        txtDestination.setText(null);
        txtDateRecuperer.setDate(null);
        txtNom.setText(null);
        txtPrenom.setText(null);
        txtPhone.setText(null);
        cmbTypePiece.setSelectedIndex(0);
        txtNumPiece.setText(null);
        numrecup.setText(null);
        btnValider.setEnabled(true);
        btnRecherche.setEnabled(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualiser;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExporter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnRecherche;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnValider;
    private javax.swing.JComboBox<String> cmbTypePiece;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField numrecup;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTable tableCourrierRecuperer;
    private javax.swing.JTextField txtDateEnvoie;
    private com.toedter.calendar.JDateChooser txtDateRecuperer;
    private javax.swing.JTextField txtDestinataire;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtExpediteur;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumPiece;
    private javax.swing.JTextField txtNumRech;
    private javax.swing.JFormattedTextField txtPhone;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtProvenance;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
