/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestioncourrier_design;

import classe.idGenerator;
import classe.user;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lankoande
 */
public final class FormUtilisateur extends javax.swing.JPanel {

    /**
     * Creates new form FormUtilisateur
     */
    private String numero = null;
    private final String getNum = null;

    public FormUtilisateur() {
        initComponents();
        affichageList();
        allDisable();
        btnSupprimer.enable(false);
        getNumMdif.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtpassUser = new javax.swing.JTextField();
        txtNameUser = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        txtNumPiece = new javax.swing.JTextField();
        txtPhone = new javax.swing.JFormattedTextField();
        cmbTypePiece = new javax.swing.JComboBox<>();
        cmbRole = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        btnNouveau = new javax.swing.JButton();
        btnValider = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        getNumMdif = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Hack", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Utilisateur");

        jLabel2.setFont(new java.awt.Font("Hack", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nom:");

        jLabel3.setFont(new java.awt.Font("Hack", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Prenom:");

        jLabel4.setFont(new java.awt.Font("Hack", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Type piece:");

        jLabel5.setFont(new java.awt.Font("Hack", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Numero de piece:");

        jLabel6.setFont(new java.awt.Font("Hack", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Telephone:");

        jLabel7.setFont(new java.awt.Font("Hack", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Role:");

        jLabel8.setFont(new java.awt.Font("Hack", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Login:");

        jLabel9.setFont(new java.awt.Font("Hack", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Mot de passe:");

        txtNom.setForeground(new java.awt.Color(51, 51, 51));
        txtNom.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtpassUser.setForeground(new java.awt.Color(51, 51, 51));
        txtpassUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNameUser.setForeground(new java.awt.Color(51, 51, 51));
        txtNameUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPrenom.setForeground(new java.awt.Color(51, 51, 51));
        txtPrenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNumPiece.setForeground(new java.awt.Color(51, 51, 51));
        txtNumPiece.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPhone.setForeground(new java.awt.Color(51, 51, 51));
        try {
            txtPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## ## ## ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cmbTypePiece.setForeground(new java.awt.Color(51, 51, 51));
        cmbTypePiece.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNIB", "PASSEPORT" }));

        cmbRole.setForeground(new java.awt.Color(51, 51, 51));
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EMPLOYER", "ADMINISTRATEUR" }));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num", "Non", "Prenom", "Telephone", "Num piece", "Login", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableUser.setRowSelectionAllowed(true);
        tableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUserMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableUserMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableUser);
        if (tableUser.getColumnModel().getColumnCount() > 0) {
            tableUser.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableUser.getColumnModel().getColumn(2).setPreferredWidth(35);
            tableUser.getColumnModel().getColumn(3).setPreferredWidth(20);
            tableUser.getColumnModel().getColumn(5).setPreferredWidth(30);
        }

        btnNouveau.setBackground(new java.awt.Color(0, 0, 51));
        btnNouveau.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        btnNouveau.setForeground(new java.awt.Color(255, 255, 255));
        btnNouveau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nouveau-compte-blanc.png"))); // NOI18N
        btnNouveau.setText("Nouveau");
        btnNouveau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNouveauMouseClicked(evt);
            }
        });

        btnValider.setBackground(new java.awt.Color(0, 0, 51));
        btnValider.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        btnValider.setForeground(new java.awt.Color(255, 255, 255));
        btnValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save-blanc.png"))); // NOI18N
        btnValider.setText("Valider");
        btnValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderMouseClicked(evt);
            }
        });

        btnAnnuler.setBackground(new java.awt.Color(0, 0, 51));
        btnAnnuler.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        btnAnnuler.setForeground(new java.awt.Color(255, 255, 255));
        btnAnnuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel-blanc.png"))); // NOI18N
        btnAnnuler.setText("Annuler");
        btnAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnnulerMouseClicked(evt);
            }
        });

        btnSupprimer.setBackground(new java.awt.Color(0, 0, 51));
        btnSupprimer.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        btnSupprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete-blanc.png"))); // NOI18N
        btnSupprimer.setText("Supprimer");
        btnSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimerMouseClicked(evt);
            }
        });

        getNumMdif.setEditable(false);
        getNumMdif.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(getNumMdif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbTypePiece, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPhone)
                                .addComponent(txtNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtpassUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNumPiece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSupprimer, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAnnuler)
                                .addComponent(btnValider)
                                .addComponent(btnNouveau))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel5, jLabel7, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbRole, txtNumPiece, txtPrenom, txtpassUser});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnnuler, btnNouveau, btnSupprimer, btnValider});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(getNumMdif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(btnNouveau)))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(txtNumPiece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTypePiece, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnValider))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAnnuler)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(txtNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpassUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSupprimer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbRole, cmbTypePiece, txtNameUser, txtNom, txtNumPiece, txtPhone, txtPrenom, txtpassUser});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAnnuler, btnNouveau, btnSupprimer, btnValider});

    }// </editor-fold>//GEN-END:initComponents

    private void btnNouveauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNouveauMouseClicked
        allEnable();
        txtNom.requestFocus();

        try {
            String numUser = "U-" + Long.toString(idGenerator.generateUniqueId());
            numero = numUser;
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FormUtilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnNouveauMouseClicked

    private void btnAnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnnulerMouseClicked
        // action apres le clique du boutton Annuler

        allDisable();
        allClear();
        btnSupprimer.enable(false);
    }//GEN-LAST:event_btnAnnulerMouseClicked

    private void btnValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderMouseClicked
        // Action apres click  du noutton valider

        if (txtNom.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Le Nom ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtNom.requestFocus();

        } else if (txtPrenom.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Le Prenom  ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtPrenom.requestFocus();

        } else if (txtNumPiece.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Le Numero de piece ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtNumPiece.requestFocus();

        } else if (txtPhone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Le numero de telephone  ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtPhone.requestFocus();

        } else if (txtNameUser.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Le Num d'utilisateur (login)  ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtNameUser.requestFocus();

        } else if (txtpassUser.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Le mot de passe ne peux pas etre vie !", "System Info", JOptionPane.WARNING_MESSAGE);
            txtpassUser.requestFocus();

        } else {
            try {
                System.out.println("Resultat de la fonction recherche = " + user.rechercheUser(numero));
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(FormUtilisateur.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                if (user.rechercheUser(numero) == false) {
                    // recuperation des valeurs
                    String nom = txtNom.getText();
                    String prenom = txtPrenom.getText();
                    String typePiece = (String) cmbTypePiece.getSelectedItem();
                    String numPiece = txtNumPiece.getText();
                    String phone = txtPhone.getText();
                    String role = (String) cmbRole.getSelectedItem();
                    String userName = txtNameUser.getText();
                    String UserPasse = txtpassUser.getText();
//                    enregistrement des donnees
                    user.validerUser(numero, nom, prenom, phone, typePiece, numPiece, userName, UserPasse, role);
                    JOptionPane.showMessageDialog(null, "Donnees de l'utilisateur [ " + userName + " ] Enregistrer !");

                    allClear();
                    allDisable();
                    affichageList();
                    btnValider.setText("Valider");

                } else if (user.rechercheUser(numero) == true) {

                    // recuperation des valeurs
                    String nom = txtNom.getText();
                    String prenom = txtPrenom.getText();
                    String typePiece = (String) cmbTypePiece.getSelectedItem();
                    String numPiece = txtNumPiece.getText();
                    String phone = txtPhone.getText();
                    String role = (String) cmbRole.getSelectedItem();
                    String userName = txtNameUser.getText();
                    String UserPasse = txtpassUser.getText();

                    //Update des donnees d'un user
                    user.UpdateUser(getNumMdif.getText(), nom, prenom, phone, typePiece, numPiece, userName, UserPasse, role);
                    JOptionPane.showMessageDialog(null, "Donnees de l'utilisateur [ " + userName + " ] Modifier !");
                    allClear();
                    allDisable();
                    affichageList();
                    btnValider.setText("Valider");

                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(FormUtilisateur.class.getName()).log(Level.SEVERE, null, ex);
            }
            allDisable();
            affichageList();
            allClear();
            btnSupprimer.enableInputMethods(false);
        }
    }//GEN-LAST:event_btnValiderMouseClicked

    private void tableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUserMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) tableUser.getModel();
        int tIndex = tableUser.getSelectedRow();
        getNumMdif.setText(dtm.getValueAt(tIndex, 0).toString());
        numero = dtm.getValueAt(tIndex, 0).toString();

        try {

            if (null != user.getOneUser(getNumMdif.getText())) {
                String[] result = user.getOneUser(getNumMdif.getText());
                txtNom.setText(result[0]);
                txtPrenom.setText(result[1]);
                if (result[2].equals("CNIB")) {
                    cmbTypePiece.setSelectedIndex(0);
                } else {
                    cmbTypePiece.setSelectedIndex(1);
                }
                txtNumPiece.setText(result[3]);
                txtPhone.setText(result[4]);
                if (result[5].equals("ADMINISTRATEUR")) {
                    cmbRole.setSelectedIndex(1);
                } else {
                    cmbRole.setSelectedIndex(0);
                }
                txtNameUser.setText(result[6]);
                txtpassUser.setText(result[7]);
            }

            allEnable();
            btnSupprimer.enableInputMethods(true);
            btnValider.setText("Modifier");
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(FormUtilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tableUserMouseClicked

    private void btnSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMouseClicked
        try {
            if (JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment Supprimer l'utilisateur [ " + txtNameUser.getText() + " ]", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                user.DeleteUsers(getNumMdif.getText());
                allClear();
                allDisable();
                affichageList();
                btnValider.setText("Valider");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FormUtilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSupprimerMouseClicked

    private void tableUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUserMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableUserMousePressed

    public void allEnable() { // fonction d'activation des champs
        txtNom.enable(true);
        txtPrenom.enable(true);
        cmbTypePiece.enable(true);
        txtNumPiece.enable(true);
        txtPhone.enable(true);
        cmbRole.enable(true);
        txtNameUser.enable(true);
        txtpassUser.enable(true);

        btnAnnuler.enable(true);
        btnValider.enable(true);
    }

    public void allDisable() { //fonction de desactivation des champs
        txtNom.enable(false);
        txtPrenom.enable(false);
        cmbTypePiece.enable(false);
        txtNumPiece.enable(false);
        txtPhone.enable(false);
        cmbRole.enable(false);
        txtNameUser.enable(false);
        txtpassUser.enable(false);

        btnAnnuler.enable(false);
        btnValider.enable(false);
    }

    public void allClear() { //fonction de clear des champs
        txtNom.setText(null);
        txtPrenom.setText(null);
        cmbTypePiece.setSelectedIndex(0);
        txtNumPiece.setText(null);
        txtPhone.setText(null);
        cmbRole.setSelectedIndex(0);
        txtNameUser.setText(null);
        txtpassUser.setText(null);
        btnValider.setText("Valider");

    }

    public void affichageList() {
        DefaultTableModel tm = (DefaultTableModel) tableUser.getModel();
        tm.setRowCount(0);
        try {
            user.getListUser(tm);
            if (tableUser.getRowCount() != 0) {
                btnSupprimer.setEnabled(false);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(formEnvoie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnNouveau;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnValider;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JComboBox<String> cmbTypePiece;
    private javax.swing.JTextField getNumMdif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tableUser;
    private javax.swing.JTextField txtNameUser;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumPiece;
    private javax.swing.JFormattedTextField txtPhone;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtpassUser;
    // End of variables declaration//GEN-END:variables
}
